MODEL:
  # backbone part.
  BACKBONE:
    NAME: "D2ConvNeXtV2"
  CONVNEXTV2:
    IN_CHANNELS: 3
    DEPTHS: [3, 3, 27, 3]
    DIMS: [192, 384, 768, 1536]
    # https://github.com/google-research/deeplab2/blob/main/configs/coco/kmax_deeplab/kmax_meta_convnext_large_os32.textproto#L28
    DROP_PATH_RATE: 0.3
    OUT_INDICES: [0, 1, 2, 3]
  PIXEL_MEAN: [127.5, 127.5, 127.5]
  PIXEL_STD: [127.5, 127.5, 127.5]
  
  # kmax part.
  META_ARCHITECTURE: "MaXTronWCDeepLab"
  SEM_SEG_HEAD:
    NAME: "MaXTronDeepLabHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 124
    LOSS_WEIGHT: 1.0

  MAXTRON:
    WITHIN_CLIP_TRACKING_MODULE:
      ENABLE: True
      NAME: "WithinClipTrackingModule"
      NUM_STAGES: 2
      SPATIAL_LAYERS: 2
      TEMPORAL_LAYERS: 4
      TEMPORAL_ATTN_TYPE: "axial-trajectory"
      ATTN_DROP: 0.2

    TEST:
      CLASS_THRESHOLD_THING: 0.7
      CLASS_THRESHOLD_STUFF: 0.5
      PIXEL_CONFIDENCE_THRESHOLD: 0.4
      OVERLAP_THRESHOLD: 0.8
      REORDER_CLASS_WEIGHT: 1.0
      REORDER_MASK_WEIGHT: 1.0
      INFERENCE_TYPE: 'clip-wise'
      POST_PROCESSING_TYPE: 'mask-wise'
      MEM_WEIGHT: 0.0
      COST_LIMIT: 0.5

  KMAX_DEEPLAB:
    SAVE_VIS_NUM: 0
    SHARE_FINAL_MATCHING: True
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 1e-5
    CLASS_WEIGHT: 4.0
    DICE_WEIGHT: 5.0
    MASK_WEIGHT: 0.01
    INSDIS_WEIGHT: 1.0
    AUX_SEMANTIC_WEIGHT: 1.0
    PIXEL_INSDIS_TEMPERATURE: 1.8
    AUX_SEMANTIC_TEMPERATURE: 2.4

    PIXEL_DEC:
      NAME: "kMaXPixelDecoder"
      IN_FEATURES: ["res2", "res3", "res4", "res5"]
      DEC_LAYERS: [1, 5, 1, 1]
      LAYER_TYPES: ["axial", "axial", "bottleneck", "bottleneck"]
      DEC_CHANNELS: [512, 256, 128, 64]

    TRANS_DEC:
      NAME: "MaXTronTransformerDecoder"
      DEC_LAYERS: [2, 2, 2]
      NUM_OBJECT_QUERIES: 128
      IN_CHANNELS: [2048, 1024, 512] # [512 * 4, 256 * 4, 128 * 4]
      DROP_PATH_PROB: 0.2

DATASETS:
  TRAIN: ("panoVSPW_vps_video_train",)
  TEST: ("panoVSPW_vps_video_val",)
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.00005
  LR_SCHEDULER_NAME: "TF2WarmupPolyLR"
  MAX_ITER: 30000
  WARMUP_ITERS: 1500
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  SPATIAL_MULTIPLIER: 1.0
  TEMPORAL_MULTIPLIER: 2.0
  CLIP_GRADIENTS:
    ENABLED: False
  AMP:
    ENABLED: True
  CHECKPOINT_PERIOD: 10000
INPUT:
  IMAGE_SIZE: [769, 1345]
  MIN_SCALE: 0.3
  MAX_SCALE: 1.7
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "vipseg_panoptic_mapper"
  MIN_SIZE_TEST: 769
  MAX_SIZE_TEST: 1345
  # video
  NUM_CLIP_FRAMES: 2
  NUM_VIDEO_FRAMES: 2
TEST:
  EVAL_PERIOD: 5000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
VERSION: 2