_BASE_: kmax_r50.yaml
MODEL:
  # backbone part.
  BACKBONE:
    NAME: "D2ConvNeXtV2"
  WEIGHTS: "convnextv2_huge_22k_512_ema.pkl"
  CONVNEXTV2:
    IN_CHANNELS: 3
    DEPTHS: [3, 3, 27, 3]
    DIMS: [352, 704, 1408, 2816]
    # https://github.com/google-research/deeplab2/blob/main/configs/coco/kmax_deeplab/kmax_meta_convnext_large_os32.textproto#L28
    DROP_PATH_RATE: 0.6
    OUT_INDICES: [0, 1, 2, 3]