_BASE_: kmax_r50.yaml
MODEL:
  # backbone part.
  BACKBONE:
    NAME: "D2ConvNeXtV2"
  WEIGHTS: "convnextv2_large_22k_384_ema.pkl"
  CONVNEXTV2:
    IN_CHANNELS: 3
    DEPTHS: [3, 3, 27, 3]
    DIMS: [192, 384, 768, 1536]
    # https://github.com/google-research/deeplab2/blob/main/configs/coco/kmax_deeplab/kmax_meta_convnext_large_os32.textproto#L28
    DROP_PATH_RATE: 0.6
    OUT_INDICES: [0, 1, 2, 3]
  KMAX_DEEPLAB:
    WITHIN_CLIP_TRACKING_MODULE:
      ENABLE: True
      NAME: "WithinClipTrackingModule"
      SPATIAL_LAYERS: 2
  