# -*- coding: utf-8 -*-
from detectron2.config import CfgNode as CN


def add_maxtron_deeplab_config(cfg):
    """
    Add config for MaXTron.
    """
    # NOTE: configs from original maskformer
    
    # video data
    # DataLoader
    cfg.INPUT.AUGMENTATIONS = [] # "brightness", "contrast", "saturation", "rotation"
    # RANDOM REVERSE
    cfg.INPUT.RANDOM_REVERSE = False
    
    # MaXTron model config
    cfg.MODEL.MAXTRON = CN()

    # within-clip tracking module config
    cfg.MODEL.MAXTRON.WITHIN_CLIP_TRACKING_MODULE = CN()
    cfg.MODEL.MAXTRON.WITHIN_CLIP_TRACKING_MODULE.ENABLE = False
    cfg.MODEL.MAXTRON.WITHIN_CLIP_TRACKING_MODULE.NAME = "WithinClipTrackingModule"
    cfg.MODEL.MAXTRON.WITHIN_CLIP_TRACKING_MODULE.NHEADS = 8
    cfg.MODEL.MAXTRON.WITHIN_CLIP_TRACKING_MODULE.DIM_FEEDFORWARD = 1024
    cfg.MODEL.MAXTRON.WITHIN_CLIP_TRACKING_MODULE.CONV_DIMS = 256
    cfg.MODEL.MAXTRON.WITHIN_CLIP_TRACKING_MODULE.DROPOUT = 0.0
    cfg.MODEL.MAXTRON.WITHIN_CLIP_TRACKING_MODULE.ATTN_DROP = 0.0
    cfg.MODEL.MAXTRON.WITHIN_CLIP_TRACKING_MODULE.SPATIAL_IN_FEATURES = ['res3', 'res4', 'res5']
    cfg.MODEL.MAXTRON.WITHIN_CLIP_TRACKING_MODULE.TEMPORAL_IN_FEATURES = ['res4', 'res5']
    cfg.MODEL.MAXTRON.WITHIN_CLIP_TRACKING_MODULE.NUM_STAGES = 2
    cfg.MODEL.MAXTRON.WITHIN_CLIP_TRACKING_MODULE.SPATIAL_LAYERS = 2
    cfg.MODEL.MAXTRON.WITHIN_CLIP_TRACKING_MODULE.TEMPORAL_LAYERS = 4
    cfg.MODEL.MAXTRON.WITHIN_CLIP_TRACKING_MODULE.TEMPORAL_ATTN_TYPE = "axial_trajectory"

    # cross-clip tracking module config
    cfg.MODEL.MAXTRON.CROSS_CLIP_TRACKING_MODULE = CN()
    cfg.MODEL.MAXTRON.CROSS_CLIP_TRACKING_MODULE.ENABLE = False 
    cfg.MODEL.MAXTRON.CROSS_CLIP_TRACKING_MODULE.NUM_LAYERS = 6
    cfg.MODEL.MAXTRON.CROSS_CLIP_TRACKING_MODULE.ATTN_DROP = 0.0
    cfg.MODEL.MAXTRON.CROSS_CLIP_TRACKING_MODULE.ASPP_DROP = 0.0
    cfg.MODEL.MAXTRON.CROSS_CLIP_TRACKING_MODULE.KERNEL_SIZES = [3,3,3]
    cfg.MODEL.MAXTRON.CROSS_CLIP_TRACKING_MODULE.ATROUS_RATES = [1,2,3]
    cfg.MODEL.MAXTRON.CROSS_CLIP_TRACKING_MODULE.NORM_FN = 'ln'

    # MAXTRON inference config
    cfg.MODEL.MAXTRON.TEST = CN()
    cfg.MODEL.MAXTRON.TEST.PIXEL_CONFIDENCE_THRESHOLD = 0.3
    cfg.MODEL.MAXTRON.TEST.CLASS_THRESHOLD_THING = 0.1
    cfg.MODEL.MAXTRON.TEST.CLASS_THRESHOLD_STUFF = 0.3
    cfg.MODEL.MAXTRON.TEST.OVERLAP_THRESHOLD = 0.8
    cfg.MODEL.MAXTRON.TEST.REORDER_CLASS_WEIGHT = 1.0
    cfg.MODEL.MAXTRON.TEST.REORDER_MASK_WEIGHT = 1.0
    cfg.MODEL.MAXTRON.TEST.INFERENCE_TYPE = "clip-wise"
    cfg.MODEL.MAXTRON.TEST.POST_PROCESSING_TYPE = "mask-wise"
    cfg.MODEL.MAXTRON.TEST.MEM_WEIGHT = 0.0
    cfg.MODEL.MAXTRON.TEST.COST_LIMIT = 0.5

    # CC_Tracking prediction_head_multiplier
    cfg.SOLVER.SPATIAL_MULTIPLIER = 1.0
    cfg.SOLVER.TEMPORAL_MULTIPLIER = 2.0
    cfg.SOLVER.PREDICTION_HEAD_MULTIPLIER = 0.1

    # Input config
    cfg.INPUT.IMAGE_SIZE = [1281, 1281]
    cfg.INPUT.MIN_SCALE = 0.3
    cfg.INPUT.MAX_SCALE = 1.7
    cfg.INPUT.NUM_VIDEO_FRAMES = 24
    cfg.INPUT.NUM_CLIP_FRAMES = 2

